name: Manual Windows Build

on:
  workflow_dispatch:

jobs:
  build-windows-manual:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build
    
    - name: Generate Windows resources
      run: |
        go install github.com/akavel/rsrc@latest
        rsrc -manifest build/windows/gpp.exe.manifest -ico build/windows/icon.ico -o gpp.syso
    
    - name: Build Windows executable manually
      env:
        CGO_ENABLED: 1
      run: |
        go build -tags "production windows with_quic" `
          -ldflags "-H windowsgui -s -w" `
          -o build/bin/gpp.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: gpp-windows-manual
        path: build/bin/gpp.exe